[pytest]
minversion = 9.0
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
log_cli = false
addopts = 
    --capture=fd
    --no-cov-on-fail
    --import-mode=importlib
    --strict-markers
    --tb=short
    --cov=app
    --cov-report=term-missing
    --cov-report=html
    --cache-clear
