"""
Add display_name column to users table.

Revision ID: 5f3ec632a8e7
Revises: 58283374f96c
Create Date: 2025-12-18 22:21:27.658036
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# Revision identifiers, used by Alembic
revision: str = "5f3ec632a8e7"
down_revision: str | Sequence[str] | None = "58283374f96c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes for this revision."""
    # Add display_name column
    op.add_column("users", sa.Column("display_name", sa.String(length=200), nullable=True))

    # Backfill existing data: compute display_name from first_name, last_name, or username
    connection = op.get_bind()
    connection.execute(
        text("""
            UPDATE users
            SET display_name = CASE
                WHEN first_name IS NOT NULL AND last_name IS NOT NULL
                THEN first_name || ' ' || last_name
                ELSE username
            END
            WHERE display_name IS NULL
        """),
    )


def downgrade() -> None:
    """Revert schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "display_name")
    # ### end Alembic commands ###
