"""
Add role column to users table.

Revision ID: 58283374f96c
Revises: 0001
Create Date: 2025-12-18 21:30:33.909459
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import inspect

from alembic import op

# Revision identifiers, used by Alembic
revision: str = "58283374f96c"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes for this revision."""
    # Note: The 'role' column already exists in the initial schema (0001),
    # so this migration is redundant. However, it was generated when the
    # database existed before migrations. We check if the column exists
    # before trying to add it to avoid errors on fresh databases.

    connection = op.get_bind()
    inspector = inspect(connection)
    columns = [col["name"] for col in inspector.get_columns("users")]

    # Only add role column if it doesn't exist (for databases created before initial schema)
    if "role" not in columns:
        op.add_column(
            "users",
            sa.Column("role", sa.String(length=20), server_default="user", nullable=False),
        )

    # Only create indexes if they don't exist
    indexes = [idx["name"] for idx in inspector.get_indexes("users")]
    if "ix_users_provider_id" not in indexes:
        op.create_index(op.f("ix_users_provider_id"), "users", ["provider_id"], unique=False)
    if "ix_users_role" not in indexes:
        op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)


def downgrade() -> None:
    """Revert schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_provider_id"), table_name="users")
    op.drop_column("users", "role")
    # ### end Alembic commands ###
