"""
add_user_testimonial_column.

Revision ID: 29cb6c6a497a
Revises: add_reviews_blog_videos
Create Date: 2026-02-06 09:26:49.378084

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Revision identifiers, used by Alembic
revision: str = "29cb6c6a497a"
down_revision: str | Sequence[str] | None = "add_reviews_blog_videos"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "testimonial",
            sa.String(length=500),
            nullable=True,
            comment="User testimonial",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "testimonial")
    # ### end Alembic commands ###
