"""
AI Routes.

Provides chat, email inquiry, and itinerary generation endpoints.

Summary
-------
Endpoints include:
  - Chat with AI agent
  - Send travel inquiry email with AI-generated confirmation
  - Generate travel itineraries (markdown and text)

Rate Limiting
-------------
All endpoints define explicit rate limits and include `429` response examples.
"""

from logging import getLogger
from typing import Annotated

from fastapi import APIRouter, Body, Request
from fastapi.responses import ORJSONResponse
from starlette.responses import Response

from app.configs import file_logger
from app.decorators import cached, timed
from app.dependencies import AiDep, EmailDep
from app.managers.cache_manager import cache_manager
from app.managers.rate_limiter import limiter
from app.schemas.ai.chatbot import ChatRequest, ChatResponse
from app.schemas.ai.itinerary import (
    ItineraryMD,
    ItineraryRequestMD,
    ItineraryRequestTXT,
    ItineraryTXT,
)
from app.schemas.email import ContactAnalysisResponse, EmailInquiry
from app.services.chatbot import chat_with_ai
from app.services.email_inquiry import analyze_contact, confirmation_message
from app.services.itinerary import ai_convert_txt, generate_itinerary

logger = file_logger(getLogger(__name__))

router = APIRouter(prefix="/ai", tags=["🤖 Ai"])


def itinerary_md_key(itinerary_req: ItineraryRequestMD) -> str:
    duration = itinerary_req.duration
    interests = ", ".join(itinerary_req.interests)
    budget = itinerary_req.budget
    return f"itinerary_{duration}_{interests}_{budget}"


def itinerary_txt_key(itinerary_req: ItineraryRequestTXT) -> str:
    user_name = itinerary_req.user_name
    md_id = itinerary_req.md_id
    return f"itinerary_{user_name}_{md_id}"


@router.post(
    "/chat",
    response_class=ORJSONResponse,
    summary="Chat to agent",
    response_model=ChatResponse,
    responses={
        200: {
            "content": {
                "application/json": {
                    "example": {"answer": "Bali has beautiful beaches like Nusa Dua and Kuta."},
                },
            },
        },
        429: {
            "description": "Rate limit exceeded",
            "content": {"application/json": {"example": {"detail": "Too Many Requests"}}},
        },
    },
    operation_id="ai_chat",
)
@timed("/ai/chat")
@limiter.limit("10/minute")
async def chat_bot(
    request: Request,
    response: Response,
    chat: Annotated[
        ChatRequest,
        Body(
            examples={
                "basic": {
                    "summary": "Simple chat",
                    "value": {
                        "query": "What are the best beaches in Bali?",
                        "history": [
                            {"role": "user", "parts": [{"text": "Hello"}]},
                        ],
                    },
                },
            },
        ),
    ],
    ai_client: AiDep,
) -> ORJSONResponse:
    """
    Chat to agent.

    Parameters
    ----------
    request : Request
        Current request context.
    response : Response
        Current response context.
    chat : ChatRequest
        Chat payload including query and optional history.
    ai_client : AiClient
        AI client dependency.

    Returns
    -------
    ORJSONResponse
        JSON containing `answer` generated by the AI.

    Notes
    -----
    Rate limited to 10 requests per minute.

    Examples
    --------
    Request
        POST /ai/chat
        Body: {"query": "What are the best beaches in Bali?", "history": []}
    Response
        200 OK
        {"answer": "Bali has beautiful beaches like Nusa Dua and Kuta."}

    Response schema
    ---------------
    {
      "answer": str
    }
    """
    answer = await chat_with_ai(chat, ai_client)
    return ORJSONResponse(answer.model_dump())


@router.post(
    "/email-inquiry/",
    response_class=ORJSONResponse,
    summary="Send a travel inquiry email",
    response_model=ContactAnalysisResponse,
    responses={
        200: {
            "content": {
                "application/json": {
                    "example": {"confirmation": "Inquiry received. We will get back to you soon."},
                },
            },
        },
        429: {
            "description": "Rate limit exceeded",
            "content": {"application/json": {"example": {"detail": "Too Many Requests"}}},
        },
    },
    operation_id="ai_email_inquiry",
)
@timed("/ai/email-inquiry")
@limiter.limit("5/hour")
async def email_inquiry_confirmation_message(
    request: Request,
    response: Response,
    email_inquiry: Annotated[
        EmailInquiry,
        Body(
            examples={
                "basic": {
                    "summary": "Basic inquiry",
                    "value": {
                        "name": "John Doe",
                        "subject": "Travel Inquiry",
                        "message": "I would like to book a trip to Bali for 7 days.",
                        "email": "jhondoe@gmail.com",
                    },
                },
            },
        ),
    ],
    ai_client: AiDep,
    email_client: EmailDep,
) -> ORJSONResponse:
    """
    Send a travel inquiry email.

    Parameters
    ----------
    request : Request
        Current request context.
    response : Response
        Current response context.
    email_inquiry : EmailInquiry
        Inquiry details including name, subject, message, and email.
    ai_client : AiClient
        AI client dependency.
    email_client : EmailClient
        Email client dependency.

    Returns
    -------
    ORJSONResponse
        JSON with confirmation analysis content.

    Notes
    -----
    Rate limited to 5 requests per hour.

    Examples
    --------
    Request
        POST /ai/email-inquiry/
        Body: {"name": "John Doe", "subject": "Travel Inquiry", "message": "...", "email": "jhondoe@gmail.com"}
    Response
        200 OK
        {"confirmation": "Inquiry received. We will get back to you soon."}

    Response schema
    ---------------
    {
      "confirmation": str
    }
    """

    body = await analyze_contact(request, email_inquiry, ai_client)

    await email_client.send_email(
        subject=email_inquiry.subject,
        body=body,
        reply_to=email_inquiry.email,
        is_html=True,
    )
    contact_analysis = await confirmation_message(email_inquiry, ai_client, email_sent=True)
    return ORJSONResponse(content=contact_analysis.model_dump())


@router.post(
    "/itinerary-md",
    summary="Generate an itinerary",
    response_model=ItineraryMD,
    response_class=ORJSONResponse,
    responses={
        200: {
            "content": {
                "application/json": {
                    "example": {"itinerary": "# 7-Day Bali Trip\nDay 1: Arrival..."},
                },
            },
        },
        429: {
            "description": "Rate limit exceeded",
            "content": {"application/json": {"example": {"detail": "Too Many Requests"}}},
        },
    },
    operation_id="ai_itinerary_md",
)
@timed("/ai/itinerary-md")
@limiter.limit("5/hour")
@cached(
    cache_manager,
    ttl=3600,
    key_builder=lambda itinerary_req, **kw: itinerary_md_key(itinerary_req),
    namespace="itinerary-md",
    response_model=ItineraryMD,
)
async def itinerary(
    request: Request,
    response: Response,
    itinerary_req: Annotated[
        ItineraryRequestMD,
        Body(
            examples={
                "basic": {
                    "summary": "Basic itinerary request",
                    "value": {
                        "duration": 7,
                        "interests": ["beaches", "temples"],
                        "budget": "US$ 1000",
                    },
                },
            },
        ),
    ],
    ai_client: AiDep,
) -> ItineraryMD:
    r"""
    Generate an itinerary based on the itinerary request.

    Parameters
    ----------
    request : Request
        Current request context.
    response : Response
        Current response context.
    itinerary_req : ItineraryRequestMD
        Itinerary generation parameters.
    ai_client : AiClient
        AI client dependency.

    Returns
    -------
    ItineraryMD
        Markdown itinerary content.

    Notes
    -----
    Rate limited to 5 requests per hour.

    Examples
    --------
    Request
        POST /ai/itinerary-md
        Body: {"duration": 7, "interests": ["beaches", "temples"], "budget": "US$ 1000"}
    Response
        200 OK
        {"itinerary": "# 7-Day Bali Trip\nDay 1: Arrival..."}

    Response schema
    ---------------
    {
      "itinerary": str
    }
    """
    return await generate_itinerary(request, itinerary_req, ai_client)


# this endpoint needs database implementation.
@router.post(
    "/itinerary-txt",
    response_class=ORJSONResponse,
    summary="Generate an itinerary",
    response_model=ItineraryTXT,
    include_in_schema=False,
    responses={
        200: {
            "content": {
                "application/json": {
                    "example": {"text_content": "Bali itinerary plain text..."},
                },
            },
        },
        429: {
            "description": "Rate limit exceeded",
            "content": {"application/json": {"example": {"detail": "Too Many Requests"}}},
        },
    },
    operation_id="ai_itinerary_txt",
)
@timed("/ai/itinerary-txt")
@limiter.limit("5/hour")
@cached(
    cache_manager,
    ttl=3600,
    key_builder=lambda itinerary_md, **kw: itinerary_md_key(itinerary_md),
    namespace="itinerary-txt",
    response_model=ItineraryTXT,
)
async def itinerary_txt(
    request: Request,
    response: Response,
    itinerary_md: Annotated[
        ItineraryRequestTXT,
        Body(
            examples={
                "basic": {
                    "summary": "Markdown to text",
                    "value": {
                        "user_name": "John Doe",
                        "md_id": "00000000-0000-0000-0000-000000000000",
                        "itinerary_md": "# Trip\nDay 1...",
                    },
                },
            },
        ),
    ],
    ai_client: AiDep,
) -> ItineraryTXT:
    """
    Convert an itinerary markdown to a text file.

    Parameters
    ----------
    request : Request
        Current request context.
    response : Response
        Current response context.
    itinerary_md : ItineraryRequestTXT
        Markdown itinerary payload with identifier.
    ai_client : AiClient
        AI client dependency.

    Returns
    -------
    ItineraryTXT
        WhatsApp-friendly plain text content.

    Notes
    -----
    Rate limited to 5 requests per hour.

    Examples
    --------
    Request
        POST /ai/itinerary-txt
        Body: {"user_name": "John Doe", "md_id": "...", "itinerary_md": "# Trip"}
    Response
        200 OK
        {"text_content": "Bali itinerary plain text..."}

    Response schema
    ---------------
    {
      "text_content": str
    }
    """
    return await ai_convert_txt(request, itinerary_md, ai_client)
