from app.errors.ai import (
    AiAuthenticationError,
    AIClientError,
    AiError,
    AIGenerationError,
    AiNetworkError,
    AiQuotaExceededError,
    AiResponseError,
    ContactAnalysisError,
    ItineraryGenerationError,
    QueryProcessingError,
    ai_exception_handler,
)
from app.errors.auth import (
    UserAuthenticationError,
    auth_exception_handler,
)
from app.errors.base import BASE_EXCEPTION, BaseAppError, create_exception_handler, host
from app.errors.cache import (
    CacheCompressionError,
    CacheDecompressionError,
    CacheDeserializationError,
    CacheExceptionError,
    CacheKeyError,
    CacheSerializationError,
    cache_exception_handler,
)
from app.errors.circuit_breaker import CircuitBreakerError, circuit_breaker_exception_handler
from app.errors.database import (
    DatabaseConfigurationError,
    DatabaseConnectionError,
    DatabaseError,
    DatabaseInitializationError,
    DuplicateEntryError,
    RecordNotFoundError,
    TransactionError,
    database_exception_handler,
)
from app.errors.email import (
    AuthenticationError,
    ConfigurationError,
    EmailServiceError,
    SendingError,
    email_client_exception_handler,
)
from app.errors.password_hasher import (
    PasswordHashingError,
    PasswordRehashError,
    password_hashing_exception_handler,
)
from app.errors.validation import ValidationError, validation_exception_handler

__all__ = [
    "AuthenticationError",
    "UserAuthenticationError",
    "auth_exception_handler",
    "ConfigurationError",
    "EmailServiceError",
    "SendingError",
    "CacheCompressionError",
    "CacheDecompressionError",
    "CacheDeserializationError",
    "CacheExceptionError",
    "CacheKeyError",
    "CacheSerializationError",
    "BASE_EXCEPTION",
    "email_client_exception_handler",
    "cache_exception_handler",
    "create_exception_handler",
    "BaseAppError",
    "CircuitBreakerError",
    "circuit_breaker_exception_handler",
    "PasswordHashingError",
    "PasswordRehashError",
    "password_hashing_exception_handler",
    "DatabaseError",
    "DatabaseConnectionError",
    "DatabaseConfigurationError",
    "DatabaseInitializationError",
    "DuplicateEntryError",
    "RecordNotFoundError",
    "TransactionError",
    "database_exception_handler",
    "AiError",
    "AiAuthenticationError",
    "AiQuotaExceededError",
    "AiNetworkError",
    "AiResponseError",
    "ai_exception_handler",
    "AIGenerationError",
    "AIClientError",
    "ContactAnalysisError",
    "ItineraryGenerationError",
    "QueryProcessingError",
    "ValidationError",
    "validation_exception_handler",
    "host",
]
