# app/dependencies/__init__.py

from app.dependencies.dependencies import (
    AdminUserDep,
    AiDep,
    AuthServiceDep,
    BlogListQuery,
    BlogQueryListDep,
    BlogRepoDep,
    CacheDep,
    EmailDep,
    ModeratorUserDep,
    ReviewRepoDep,
    UserDBDep,
    UserQueryListDep,
    UserRepoDep,
    UserRespDep,
    VerifiedUserDep,
    check_owner_or_admin,
    get_authorized_user,
    get_cache_manager,
    get_current_user,
    get_email_client,
    get_user_or_404,
    oauth2_scheme,
)

__all__ = [
    "AiDep",
    "AuthServiceDep",
    "AdminUserDep",
    "BlogListQuery",
    "BlogQueryListDep",
    "BlogRepoDep",
    "CacheDep",
    "EmailDep",
    "ModeratorUserDep",
    "ReviewRepoDep",
    "UserDBDep",
    "UserQueryListDep",
    "UserRepoDep",
    "UserRespDep",
    "VerifiedUserDep",
    "check_owner_or_admin",
    "get_current_user",
    "get_authorized_user",
    "get_cache_manager",
    "get_email_client",
    "get_user_or_404",
    "oauth2_scheme",
]
